# Generated by Django 4.2.5 on 2023-09-13 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_comment_author_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='templatetags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of templatetags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentator', to=settings.AUTH_USER_MODEL),
        ),
    ]
